language: julia
os:
    - osx
    - linux
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install python3-pip  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip3 install --upgrade pip  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip3 install --upgrade setuptools  ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo pip3 install zarr  ; fi
julia:
    - 1.1
    - nightly
notifications:
    email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs docs/make.jl
      after_success: skip
after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
